// GENERATED — do not edit by hand.
// Source: Pydantic models in src/spp/, exported by scripts/export_schema.py.
//
// This file is committed on purpose. It is the SPA's contract with the server:
// a schema change becomes a reviewable diff and then a compile error, instead of
// a field that is silently undefined in front of an audience.

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Note = string;
/**
 * profile field this was derived from
 */
export type Origin = string;
export type Severity = number;
export type Cited = string[];
export type Detail = string;
export type Kind = string;
export type Sentence = string;
export type Issues = CitationIssue[];
export type Ok = boolean;
export type UncitedSentences = string[];
export type UnknownCitations = string[];
export type Column = number | null;
export type Index = number;
/**
 * inclusion | exclusion
 */
export type Kind1 = string;
export type Message = string;
export type Ok1 = boolean;
export type Text = string;
export type BaselineCurve = {
  [k: string]: unknown;
}[];
export type BaselineRetention = number;
export type Change = string;
export type Disclaimer = string;
export type EligibilityAttribution = {
  [k: string]: unknown;
} | null;
export type ExampleLost = {
  [k: string]: unknown;
}[];
export type ExampleRecovered = {
  [k: string]: unknown;
}[];
export type Lost = number;
export type NetFlips = number;
export type Perturbed = number;
export type ArtifactVersion = number;
export type CohortSeedPath = string | null;
export type CohortSize = number;
export type Condition = string;
export type DurationDays = number;
export type GeneratedAt = string;
export type MasterSeed = number;
export type ScheduleName = string;
export type ScheduleVisits = number;
export type Recovered = number;
export type RetentionDelta = number;
export type Sensitivity = {
  [k: string]: unknown;
} | null;
export type SignStability = {
  [k: string]: unknown;
} | null;
export type Title = string;
export type Unchanged = number;
export type VariantCurve = {
  [k: string]: unknown;
}[];
export type VariantRetention = number;
export type BaselineCurve1 = {
  [k: string]: unknown;
}[];
export type BaselineRetained = number;
export type Label = string;
export type Baseline = "retained" | "dropped";
export type BaselineExitDay = number | null;
export type BaselineExitReason = string | null;
export type DivergedAtDay = number | null;
export type DivergedAtEvent = number | null;
export type PatientId = string;
export type Variant = "retained" | "dropped";
export type VariantExitDay = number | null;
export type VariantExitReason = string | null;
export type Lost1 = Flip[];
export type N = number;
export type Perturbed1 = number;
export type Recovered1 = Flip[];
export type Unchanged1 = number;
export type VariantCurve1 = {
  [k: string]: unknown;
}[];
export type VariantRetained = number;
export type NExcluded = number;
export type NScreened = number;
export type Criterion = string;
export type Kind2 = string;
export type ScreenedOut = number;
export type Shapley = number;
/**
 * fraction of all attributed exclusion
 */
export type ShapleyShare = number;
export type SoleReason = number;
export type Rules = RuleAttribution[];
export type Answer = string;
export type AnswerWithCitations = string;
export type Attempts = number;
export type Backend = string;
export type CitedFactIds = string[];
export type Grounded = boolean;
export type PatientId1 = string;
export type Question = string;
export type RetrievalConfidence = number;
export type Sources = string[];
export type Synthetic = boolean;
export type Note1 = string;
export type Stage =
  "symptom_onset" | "first_contact" | "diagnosis" | "treatment_start" | "follow_up" | "adverse_event" | "outcome";
export type When = string | null;
export type Diagnostics = CriterionDiagnostic[];
export type ValidExclusion = string[];
export type ValidInclusion = string[];
/**
 * 0=never taken, 1=perfect
 */
export type Adherence = number;
export type Dose = string | null;
export type Name1 = string;
export type Started = string | null;
export type CitedFactIds1 = string[];
export type Grounded1 = boolean;
export type IsProbe = boolean;
export type Order = number;
export type PatientId2 = string;
export type Prompt = string;
export type Text1 = string;
export type PanelSize = number;
export type Probes = string[];
export type Statements = PanelStatement[];
export type FactIds = string[];
export type Id = string;
export type Label1 = string;
export type PatientIds = string[];
export type StatementOrders = number[];
export type Themes = Theme[];
export type Topic = string;
export type AdherenceBaseline = number;
export type Age = number;
export type Ancestry = string | null;
export type Barriers = Barrier[];
export type Comorbidities = string[];
export type Condition1 = string;
export type Constraints = string[];
export type Goals = string[];
export type HealthLiteracy = "low" | "medium" | "high";
export type Journey = JourneyMilestone[];
export type Medications = Medication[];
export type PatientId3 = string;
export type SchemaVersion = number;
export type Sex = "female" | "male" | "other";
export type Stage1 = string | null;

export interface ArtifactsSchema {
  [k: string]: unknown;
}
/**
 * Something concrete standing between this persona and participation.
 *
 * Typed rather than a free-text list because barriers feed three consumers:
 * the dropout hazard (severity), the narration prompt (label), and the report
 * ("why did persona #3412 drop"), which needs `origin` to trace the barrier
 * back to the profile field that produced it.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "Barrier".
 */
export interface Barrier {
  name: Name;
  note?: Note;
  origin: Origin;
  severity: Severity;
}
/**
 * Result of verifying one generated answer.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "CitationCheck".
 */
export interface CitationCheck {
  cited?: Cited;
  issues?: Issues;
  ok: Ok;
  uncited_sentences?: UncitedSentences;
  unknown_citations?: UnknownCitations;
}
/**
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "CitationIssue".
 */
export interface CitationIssue {
  detail: Detail;
  kind: Kind;
  sentence?: Sentence;
}
/**
 * One criterion's parse status, addressed for an editor gutter.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "CriterionDiagnostic".
 */
export interface CriterionDiagnostic {
  column?: Column;
  index: Index;
  kind: Kind1;
  message?: Message;
  ok: Ok1;
  text: Text;
}
/**
 * A counterfactual result, defensible on its own.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "DiffReport".
 */
export interface DiffReport {
  assumptions?: Assumptions;
  baseline_curve?: BaselineCurve;
  baseline_retention: BaselineRetention;
  burden_shift?: BurdenShift;
  change: Change;
  disclaimer?: Disclaimer;
  eligibility_attribution?: EligibilityAttribution;
  example_lost?: ExampleLost;
  example_recovered?: ExampleRecovered;
  lost: Lost;
  net_flips: NetFlips;
  perturbed: Perturbed;
  provenance: RunProvenance;
  recovered: Recovered;
  retention_delta: RetentionDelta;
  sensitivity?: Sensitivity;
  sign_stability?: SignStability;
  title: Title;
  unchanged: Unchanged;
  variant_curve?: VariantCurve;
  variant_retention: VariantRetention;
}
export interface Assumptions {
  [k: string]: unknown;
}
export interface BurdenShift {
  [k: string]: number;
}
/**
 * Everything needed to reproduce the run exactly.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "RunProvenance".
 */
export interface RunProvenance {
  artifact_version?: ArtifactVersion;
  cohort_seed_path?: CohortSeedPath;
  cohort_size: CohortSize;
  condition: Condition;
  duration_days: DurationDays;
  generated_at?: GeneratedAt;
  master_seed: MasterSeed;
  schedule_name: ScheduleName;
  schedule_visits: ScheduleVisits;
}
/**
 * A paired comparison of two scenario runs.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "DiffResult".
 */
export interface DiffResult {
  baseline_curve?: BaselineCurve1;
  baseline_retained: BaselineRetained;
  baseline_summary?: BaselineSummary;
  burden_shift?: BurdenShift1;
  label: Label;
  lost?: Lost1;
  n: N;
  perturbed?: Perturbed1;
  recovered?: Recovered1;
  unchanged?: Unchanged1;
  variant_curve?: VariantCurve1;
  variant_retained: VariantRetained;
  variant_summary?: VariantSummary;
}
export interface BaselineSummary {
  [k: string]: unknown;
}
export interface BurdenShift1 {
  [k: string]: number;
}
/**
 * One persona whose outcome changed. The unit of a counterfactual finding.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "Flip".
 */
export interface Flip {
  baseline: Baseline;
  baseline_exit_day?: BaselineExitDay;
  baseline_exit_reason?: BaselineExitReason;
  diverged_at_day?: DivergedAtDay;
  diverged_at_event?: DivergedAtEvent;
  patient_id: PatientId;
  variant: Variant;
  variant_exit_day?: VariantExitDay;
  variant_exit_reason?: VariantExitReason;
}
export interface VariantSummary {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "EligibilityAttribution".
 */
export interface EligibilityAttribution1 {
  n_excluded: NExcluded;
  n_screened: NScreened;
  rules?: Rules;
}
/**
 * Exact Shapley value of one criterion in the exclusion veto game.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "RuleAttribution".
 */
export interface RuleAttribution {
  criterion: Criterion;
  kind: Kind2;
  screened_out: ScreenedOut;
  shapley: Shapley;
  shapley_share: ShapleyShare;
  sole_reason: SoleReason;
}
/**
 * One question and its verified answer.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "InterviewTurn".
 */
export interface InterviewTurn {
  answer: Answer;
  answer_with_citations: AnswerWithCitations;
  attempts?: Attempts;
  backend?: Backend;
  check?: CitationCheck | null;
  cited_fact_ids?: CitedFactIds;
  grounded?: Grounded;
  patient_id: PatientId1;
  question: Question;
  retrieval_confidence?: RetrievalConfidence;
  sources?: Sources;
  synthetic?: Synthetic;
}
/**
 * A single event on the patient journey (onset -> diagnosis -> treatment -> ...).
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "JourneyMilestone".
 */
export interface JourneyMilestone {
  note?: Note1;
  stage: Stage;
  when?: When;
}
/**
 * Parse result usable while the text is still being typed.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "LenientParse".
 */
export interface LenientParse {
  diagnostics?: Diagnostics;
  valid_exclusion?: ValidExclusion;
  valid_inclusion?: ValidInclusion;
}
/**
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "Medication".
 */
export interface Medication {
  adherence?: Adherence;
  dose?: Dose;
  name: Name1;
  started?: Started;
}
/**
 * One persona's turn in the transcript.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "PanelStatement".
 */
export interface PanelStatement {
  cited_fact_ids?: CitedFactIds1;
  grounded?: Grounded1;
  is_probe?: IsProbe;
  order: Order;
  patient_id: PatientId2;
  prompt: Prompt;
  text: Text1;
}
/**
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "PanelTranscript".
 */
export interface PanelTranscript {
  panel_size: PanelSize;
  probes?: Probes;
  statements?: Statements;
  themes?: Themes;
  topic: Topic;
}
/**
 * A group of statements sharing cited facts. Attribution is mechanical.
 *
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "Theme".
 */
export interface Theme {
  fact_ids?: FactIds;
  id: Id;
  label: Label1;
  patient_ids?: PatientIds;
  statement_orders?: StatementOrders;
}
/**
 * This interface was referenced by `ArtifactsSchema`'s JSON-Schema
 * via the `definition` "PatientDNA".
 */
export interface PatientDNA {
  adherence_baseline?: AdherenceBaseline;
  age: Age;
  ancestry?: Ancestry;
  barriers?: Barriers;
  biomarkers?: Biomarkers;
  comorbidities?: Comorbidities;
  condition: Condition1;
  constraints?: Constraints;
  goals?: Goals;
  health_literacy?: HealthLiteracy;
  journey?: Journey;
  medications?: Medications;
  patient_id: PatientId3;
  schema_version?: SchemaVersion;
  sex: Sex;
  social_determinants?: SocialDeterminants;
  stage?: Stage1;
  traits?: Traits;
}
export interface Biomarkers {
  [k: string]: number;
}
/**
 * e.g. {'transport': 'none', 'caregiver': 'spouse', 'employment': 'shift-work'}
 */
export interface SocialDeterminants {
  [k: string]: string;
}
export interface Traits {
  [k: string]: number;
}
