#!/usr/bin/env sh
# Regenerate requirements.txt from uv.lock. THE one command.
#
# The chain is declaration -> resolution -> consumption, each stage the input to
# the next and none of them a second copy:
#
#   pyproject.toml [project.dependencies]   declares what we depend on
#   uv.lock                                 resolves it, across every supported
#                                           interpreter, with hashes
#   requirements.txt                        renders the lock for plain pip
#
# requirements.txt stays because every documented install path uses it — README,
# both workflows, the Playwright webServer bootstrap, and the reader who clones
# the repo and wants `pip install -r requirements.txt` to work without first
# installing uv. It is a projection of the lock, not a list anyone maintains.
# Projections cannot drift as long as the sync is enforced, which is what the
# dependency-sync step in .github/workflows/tests.yml does: regenerate, diff,
# fail on any difference. Staleness is caught by construction, not convention.
#
# One export, not one per interpreter: uv emits environment markers
#   numpy==2.4.6 ; python_full_version < '3.12'
#   numpy==2.5.2 ; python_full_version >= '3.12'
# so a single file is correct on every supported version. (numpy 2.5 requires
# 3.12+, which is why this matters at all.)
#
# Hashes are included and pip verifies them, so the promise covers the artifact
# and not merely the version. Note that hash-checking mode makes pip refuse
# anything unlisted — which is why the export carries transitive dependencies
# too, and why a missing one breaks loudly rather than silently.
set -eu

cd "$(dirname "$0")/.."

# Fixed argument list: uv stamps the invoking command into the file's header, so
# varying the flags would change the bytes without changing the dependencies.
uv export --format requirements-txt --no-emit-project --output-file requirements.txt --quiet

# Prepend the pointer. "Do not edit" without the alternative just relocates the
# mistake to a fork of this script.
python3 - <<'PY'
import pathlib

BANNER = """# GENERATED FROM uv.lock — do not edit this file.
# To add or change a dependency:
#   1. edit [project.dependencies] in pyproject.toml
#   2. run  uv lock
#   3. run  scripts/sync_deps.sh
# CI regenerates this file and fails on any difference.
"""

path = pathlib.Path("requirements.txt")
text = path.read_text()
if not text.startswith(BANNER):
    path.write_text(BANNER + text)
PY

echo "requirements.txt regenerated from uv.lock"
